### PR TITLE
TRITON-1943 add Jenkinsfiles to Triton release repositories

### PR DESCRIPTION
**Pull request by trentm**

### CODE REVIEW

**Comment by trentm** [comment]
Happy to defer. Definitely this one is special.

> I think we should have a way for users to pass all of the configure-branches and build.spec.local parameters still

However, a little challenge: Have you ever used that feature?  Basically I find the headnode builds so large that the only way I've found to usefully have custom headnode builds is to build them locally and use COAL (or whatever local setup I have for running Triton).

**Comment by timfoster** [comment]
I've never needed build.spec.local, but I have often used configure-branches to get a custom Triton image with a specific platform image, or set of images included out of the box.  

Local builds here are fast only if I also happen to have built all required images locally as well (and I have to be really committed to do that!) otherwise fetching each image from manta during the build takes a loong time, sadly.

**Comment by trentm** [comment]
> I have often used configure-branches to get a custom Triton image with a specific platform image, or set of images included out of the box.

sold

**Comment by trentm** [comment]
I believe this is obsolete. Tim has moved the Jenkinsfile work for sdc-headnode out of TRITON-1943 and over to TRITON-1961.   @timfoster  correct me if I'm wrong.

**Pull request closed without merging**
