### PR TITLE
joyent/sdc-headnode#5 Fix README.md

### PR DESCRIPTION
**Pull request by nshalman**
Typo wasted a bunch of my time... :(

### CODE REVIEW

**Comment by lloydde** [comment]
It might make more sense to fix the typo on the consumer side.

**Comment by nshalman** [comment]
The other instances in the documentation are correct, I just happened to have copy-and-pasted the one incorrect one. Only when it failed to work did I go back and dig up the inconsistency.

If you mean having the consuming code accept the typo version as well as the correct version, that's a lot of work that I'm not personally inclined to do at the moment.

If that's not what you meant, then I'm really not sure what you mean and would appreciate clarification.

**Comment by lloydde** [comment]
Sorry, for not being clear. I meant to suggest that it seems likely that people will make the mistaken again in the future. answers-file makes more sense as the file name is answer**s**.json.

**Comment by bahamat** [comment]
If it's going to be changed, I think either form should be supported. Possibly temporarily, with the old one deprecated with a warning. Those of us who use it might be in for a surprise when it stops working as-is.

**Comment by lloydde** [comment]
:+1: , of course @bahamat .

**Comment by nshalman** [comment]
Well, as I said, I have no intention of digging into this code base. I wanted to fix a typo in the documentation that wasted my time.

I think supporting both forms should be a new issue (that can reference this one), and this fix should either be applied now to protect the next person from tripping over it in the meantime.

**Comment by nshalman** [comment]
Ping! Can someone please merge this already? Improving the code is a separate issue.

**Comment by trentm** [comment]
Sorry for the delay. Merged in commit 2537ecdfa984ba5ff3d794cf6f75ddb59c8a1854 and support for 'answers-file' added in commit 9de10eb68b5887f18ff7e55e5292ce2fd154a3d6.

**Comment by nshalman** [comment]
Thank you @trentm!

**Pull request closed without merging**
