### PR TITLE
OS-8370 Welcome MNX

### PR DESCRIPTION
**Pull request by bahamat**

### CODE REVIEW

**Review by danmcd — COMMENTED** [review]
Are you able to test this?  As part of RFD 176 work I've built sdc-headnode locally in the past.  It's been a while, but I can help with building (and testing on my headnode-from-ISO VM).

**Comment by danmcd** [comment]
Also, smartos-live has a moral equivalent to fix as well.

**Review by danmcd — COMMENTED** [review]
Do docs.joyent.com URLs need  to change yet?

**Comment by bahamat** [comment]
I've got another PR for smartos-live coming up.

For docs.joyent.com, those will change after the docs are stood up under the new domain.

**Review by danmcd — APPROVED** [review]

**Pull request merged**
