### PR TITLE
TRITON-2175 Have joysetup try formatting the pool with an ESP

### PR DESCRIPTION
**Pull request by danmcd**

### CODE REVIEW

**Comment by bahamat** [comment]
I'm good with this. AFAIK, there's no down side to having ESP available, even if it's not used. Where it's broken we've got the fallback, so this should be totally fine.

**Comment by danmcd** [comment]
I've upgraded this PR from draft to full.  Please review.  I need to deploy this to make sure it works on a VMware CN I use for these sorts of tests.

**Comment by danmcd** [comment]
Testing notes added to ticket.

**Comment by danmcd** [comment]
> I'm good with this. AFAIK, there's no down side to having ESP available, even if it's not used. Where it's broken we've got the fallback, so this should be totally fine.

Please officially +1 this if it's the case?

**Review by bahamat — APPROVED** [review]

**Pull request merged**
